# Generated by Django 3.2.3 on 2022-06-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='DeliveryAddress',
        ),
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
